import { formatCurrency, computeLineTotal, computeQuotationTotals } from "@/lib/utils/formatters";

const PRIMARY = "#1e40af";
const GRAY = "#6b7280";
const LIGHT_GRAY = "#f3f4f6";
const BORDER = "#d1d5db";

export async function generateQuotationPdf({ customer, quotation, items, quotationId }) {
  const [{ jsPDF }, { applyPlugin }] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);
  applyPlugin(jsPDF);
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;

  let y = margin;

  function addSectionTitle(text) {
    doc.setFillColor(PRIMARY);
    doc.rect(margin, y, contentWidth, 8, "F");
    doc.setTextColor("#ffffff");
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.text(text, margin + 3, y + 5.5);
    y += 12;
    doc.setTextColor("#000000");
  }

  function addField(label, value) {
    if (!value) return;
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(GRAY);
    doc.text(label + ":", margin + 2, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor("#000000");
    doc.text(String(value), margin + 40, y);
    y += 5;
  }

  function checkPageOverflow(needed) {
    if (y + needed > doc.internal.pageSize.getHeight() - 25) {
      doc.addPage();
      y = margin;
    }
  }

  doc.setFillColor("#f8fafc");
  doc.rect(0, 0, pageWidth, 40, "F");

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(PRIMARY);
  doc.text("QUOTATION", margin, 18);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(GRAY);
  doc.text("Quotation Manager", margin, 26);
  doc.text("Sales Quotation", margin, 31);

  if (quotationId) {
    doc.setFont("helvetica", "bold");
    doc.setTextColor("#000000");
    doc.text(`Ref: ${quotationId}`, pageWidth - margin, 18, { align: "right" });
  }

  if (quotation.quotationDate) {
    doc.setFont("helvetica", "normal");
    doc.setTextColor(GRAY);
    doc.text(`Date: ${quotation.quotationDate}`, pageWidth - margin, 26, { align: "right" });
  }

  y = 50;

  addSectionTitle("Bill To");

  const addressLines = (customer.fullAddressGst || "").split("\n");
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("Customer:", margin + 2, y + 4);
  doc.setFont("helvetica", "normal");
  doc.text(customer.customerName || "", margin + 25, y + 4);

  let addrY = y + 4;
  for (const line of addressLines) {
    addrY += 5;
    doc.text(line, margin + 25, addrY);
  }

  y = addrY + 5;

  addField("Contact Person", customer.contactPerson);
  addField("Contact Number", customer.contactNumber);
  addField("Email", customer.emailTo);
  if (customer.emailCc) addField("Email CC", customer.emailCc);
  addField("Designation", customer.designation);
  if (customer.location) addField("Location", customer.location);
  if (customer.userId) addField("User ID", customer.userId);

  y += 3;

  addSectionTitle("Quotation Details");

  const details = [
    ["Division", quotation.division],
    ["Source of Enquiry", quotation.sourceOfEnquiry],
    ["Enquiry Generated By", quotation.enquiryGeneratedBy],
    ["Party Ref No", quotation.partyReferenceNumber],
    ["Party Ref Date", quotation.partyReferenceDate],
    ["Payment Terms", quotation.paymentTerms],
    ["Quotation Validity", quotation.quotationValidity],
    ["Terms of Delivery", quotation.termsOfDelivery],
    ["Follow-up By", quotation.quotationFollowUpBy],
    ["Revise No", quotation.reviseNumber],
  ];

  const half = Math.ceil(details.filter(([, v]) => v).length / 2);
  let col1Y = y;
  let col2Y = y;

  details.forEach(([label, value], i) => {
    if (!value) return;
    const target = i < half ? "col1" : "col2";
    const x = target === "col1" ? margin + 2 : margin + contentWidth / 2 + 5;
    const yy = target === "col1" ? col1Y : col2Y;

    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(GRAY);
    doc.text(label + ":", x, yy);
    doc.setFont("helvetica", "normal");
    doc.setTextColor("#000000");
    doc.text(String(value), x + 50, yy);

    if (target === "col1") col1Y += 5;
    else col2Y += 5;
  });

  y = Math.max(col1Y, col2Y) + 5;

  if (customer.engineerRemark) {
    checkPageOverflow(10);
    addSectionTitle("Engineer Remark");
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    const remarkLines = doc.splitTextToSize(customer.engineerRemark, contentWidth - 4);
    doc.text(remarkLines, margin + 2, y);
    y += remarkLines.length * 4 + 4;
  }

  checkPageOverflow(60);

  addSectionTitle("Items");

  const tableHeaders = [
    ["#", "Part No", "Description", "Qty", "Unit Price", "Other Rate", "Disc %", "Total"],
  ];

  const tableRows = items.map((item, i) => [
    String(i + 1),
    item.partNumber,
    item.partDescription,
    String(item.quantity || 0),
    formatCurrency(item.unitPrice || 0),
    formatCurrency(item.otherRate || 0),
    item.discount ? `${item.discount}%` : "-",
    formatCurrency(computeLineTotal(item)),
  ]);

  doc.autoTable({
    head: tableHeaders,
    body: tableRows,
    startY: y,
    margin: { left: margin, right: margin },
    tableWidth: contentWidth,
    styles: {
      fontSize: 8,
      cellPadding: 2,
      lineColor: BORDER,
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: PRIMARY,
      textColor: "#ffffff",
      fontStyle: "bold",
      fontSize: 8,
    },
    columnStyles: {
      0: { cellWidth: 8, halign: "center" },
      1: { cellWidth: 30 },
      2: { cellWidth: "max" },
      3: { cellWidth: 14, halign: "center" },
      4: { cellWidth: 22, halign: "right" },
      5: { cellWidth: 22, halign: "right" },
      6: { cellWidth: 14, halign: "center" },
      7: { cellWidth: 25, halign: "right" },
    },
    alternateRowStyles: {
      fillColor: LIGHT_GRAY,
    },
  });

  y = doc.lastAutoTable.finalY + 10;

  const totals = computeQuotationTotals(items);

  const summaryX = pageWidth - margin - 80;
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  const summaryLines = [
    ["Subtotal:", formatCurrency(totals.subtotal)],
    ["Other Charges:", formatCurrency(totals.otherCharges)],
    ["Discount:", `- ${formatCurrency(totals.discountTotal)}`],
  ];

  summaryLines.forEach(([label, value], i) => {
    const yy = y + i * 7;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(GRAY);
    doc.text(label, summaryX, yy);
    doc.setFont("helvetica", "normal");
    doc.setTextColor("#000000");
    doc.text(value, pageWidth - margin, yy, { align: "right" });
  });

  y += summaryLines.length * 7 + 3;

  doc.setFillColor(PRIMARY);
  doc.rect(summaryX - 3, y - 4, pageWidth - margin - summaryX + 3, 10, "F");
  doc.setFont("helvetica", "bold");
  doc.setTextColor("#ffffff");
  doc.setFontSize(11);
  doc.text("Grand Total:", summaryX, y + 3);
  doc.text(formatCurrency(totals.grandTotal), pageWidth - margin, y + 3, { align: "right" });

  y += 20;

  doc.setFontSize(8);
  doc.setTextColor(GRAY);
  doc.text("This is a computer-generated quotation.", margin, y);
  doc.text(`Generated on: ${new Date().toLocaleString("en-IN")}`, margin, y + 4);

  doc.save(`${quotationId || "quotation"}.pdf`);
}
