import { z } from "zod";

// Split into sub-schemas so future modules (e.g. a standalone "Customer"
// entity) can reuse pieces without duplicating rules.

export const customerInfoSchema = z.object({
  customerName: z.string().trim().min(1, "Customer name is required"),
  fullAddressGst: z.string().trim().min(1, "Address & GST details are required"),
  contactPerson: z.string().trim().min(1, "Contact person is required"),
  contactNumber: z
    .string()
    .trim()
    .min(1, "Contact number is required")
    .regex(/^[0-9+\-\s()]{7,20}$/, "Enter a valid contact number"),
  designation: z.string().trim().optional().default(""),
  emailTo: z.string().trim().min(1, "Email (To) is required").email("Enter a valid email address"),
  emailCc: z
    .string()
    .trim()
    .optional()
    .default("")
    .refine((val) => val === "" || /^[^\s,]+@[^\s,]+\.[^\s,]+(\s*,\s*[^\s,]+@[^\s,]+\.[^\s,]+)*$/.test(val), {
      message: "Enter one or more valid, comma-separated email addresses",
    }),
  location: z.string().trim().optional().default(""),
  engineerRemark: z.string().trim().optional().default(""),
  userId: z.string().trim().min(1, "User ID is required"),
});

export const quotationInfoSchema = z.object({
  division: z.string().trim().min(1, "Division is required"),
  sourceOfEnquiry: z.string().trim().min(1, "Source of enquiry is required"),
  enquiryGeneratedBy: z.string().trim().min(1, "Enquiry generated by is required"),
  quotationDate: z.string().trim().min(1, "Quotation date is required"),
  partyReferenceNumber: z.string().trim().optional().default(""),
  partyReferenceDate: z.string().trim().optional().default(""),
  paymentTerms: z.string().trim().min(1, "Payment terms are required"),
  quotationValidity: z.string().trim().min(1, "Quotation validity is required"),
  termsOfDelivery: z.string().trim().min(1, "Terms of delivery are required"),
  quotationFollowUpBy: z.string().trim().optional().default(""),
  reviseNumber: z.string().trim().optional().default(""),
});

export const itemRowSchema = z.object({
  id: z.string(),
  partNumber: z.string().trim().min(1, "Part number is required"),
  partDescription: z.string().trim().min(1, "Description is required"),
  quantity: z.coerce.number({ invalid_type_error: "Quantity must be a number" }).positive("Must be greater than 0"),
  unitPrice: z.coerce.number({ invalid_type_error: "Unit price must be a number" }).nonnegative("Cannot be negative"),
  otherRate: z.coerce.number({ invalid_type_error: "Must be a number" }).nonnegative("Cannot be negative").optional().default(0),
  discount: z.coerce.number({ invalid_type_error: "Must be a number" }).min(0, "Cannot be negative").max(100, "Cannot exceed 100%").optional().default(0),
  availability: z.string().trim().optional().default(""),
  priceWef: z.string().trim().optional().default(""),
  liveStock: z.string().trim().optional().default(""),
});

export const quotationSchema = z.object({
  customer: customerInfoSchema,
  quotation: quotationInfoSchema,
  items: z.array(itemRowSchema).min(1, "Add at least one item"),
});

/**
 * Runs the schema and reshapes zod's error tree into a flat map keyed by
 * "section.field" (or "items.<index>.<field>") so form components can look
 * up a single error string per input.
 */
export function validateQuotation(payload) {
  const result = quotationSchema.safeParse(payload);
  if (result.success) {
    return { success: true, data: result.data, errors: {} };
  }

  const errors = {};
  for (const issue of result.error.issues) {
    const path = issue.path.join(".");
    if (!errors[path]) errors[path] = issue.message;
  }
  return { success: false, data: null, errors };
}
