import { z } from "zod";
import { DEFAULT_UOM, DEFAULT_GST_RATE } from "@/lib/constants/quotationOptions";

// Split into sub-schemas so future modules (e.g. a standalone "Customer"
// entity) can reuse pieces without duplicating rules.

// Custom validator for DD/MM/YYYY date format
const canonicalDateSchema = z.string()
  .trim()
  .refine((val) => val !== "", {
    message: "This field is required",
  })
  .refine((val) => /^\d{1,2}\/\d{1,2}\/\d{4}$/.test(val), {
    message: "Date must be in DD/MM/YYYY format",
  })
  .refine((val) => {
    const match = val.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
    if (!match) return false;
    const [, d, m, y] = match.map(Number);
    if (m < 1 || m > 12) return false;
    if (d < 1 || d > 31) return false;
    // Basic validation - more sophisticated validation could check month-specific days
    const date = new Date(y, m - 1, d);
    return date.getFullYear() === y && date.getMonth() === m - 1 && date.getDate() === d;
  }, {
    message: "Enter a valid date",
  });

// Optional date field validator (allows empty string)
const optionalCanonicalDateSchema = z.string()
  .trim()
  .optional()
  .default("")
  .refine((val) => val === "" || /^\d{1,2}\/\d{1,2}\/\d{4}$/.test(val), {
    message: "Date must be in DD/MM/YYYY format",
  })
  .refine((val) => {
    if (val === "") return true;
    const match = val.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
    if (!match) return false;
    const [, d, m, y] = match.map(Number);
    if (m < 1 || m > 12) return false;
    if (d < 1 || d > 31) return false;
    const date = new Date(y, m - 1, d);
    return date.getFullYear() === y && date.getMonth() === m - 1 && date.getDate() === d;
  }, {
    message: "Enter a valid date",
  });

export const customerInfoSchema = z.object({
  customerName: z.string().trim().min(1, "Customer name is required"),
  fullAddressGst: z.string().trim().min(1, "Address & GST details are required"),
  fullAddress: z.string().trim().optional().default(""),
  gstNo: z.string().trim().optional().default(""),
  stateName: z.string().trim().optional().default(""),
  stateCode: z.string().trim().optional().default(""),
  contactPerson: z.string().trim().min(1, "Contact person is required"),
  contactNumber: z
    .string()
    .trim()
    .min(1, "Contact number is required")
    .regex(/^[0-9+\-\s()]{7,20}$/, "Enter a valid contact number"),
  designation: z.string().trim().optional().default(""),
  emailTo: z
    .string()
    .trim()
    .optional()
    .default("")
    .refine((val) => val === "" || /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(val), {
      message: "Enter a valid email address",
    }),
  emailCc: z
    .string()
    .trim()
    .optional()
    .default("")
    .refine((val) => val === "" || /^[^\s,]+@[^\s,]+\.[^\s,]+(\s*,\s*[^\s,]+@[^\s,]+\.[^\s,]+)*$/.test(val), {
      message: "Enter one or more valid, comma-separated email addresses",
    }),
  location: z.string().trim().optional().default(""),
  engineerRemark: z.string().trim().optional().default(""),
  userId: z.string().trim().optional().default(""),
});

export const quotationInfoSchema = z.object({
  division: z.string().trim().min(1, "Division is required"),
  sourceOfEnquiry: z.string().trim().min(1, "Source of enquiry is required"),
  enquiryGeneratedBy: z.string().trim().min(1, "Enquiry generated by is required"),
  quotationDate: canonicalDateSchema,
  partyReferenceNumber: z.string().trim().optional().default(""),
  partyReferenceDate: optionalCanonicalDateSchema,
  paymentTerms: z.string().trim().min(1, "Payment terms are required"),
  quotationValidity: z.string().trim().min(1, "Quotation validity is required"),
  termsOfDelivery: z.string().trim().min(1, "Terms of delivery is required"),
  quotationFollowUpBy: z.string().trim().optional().default(""),
  reviseNumber: z.string().trim().optional().default(""),
});

export const itemRowSchema = z.object({
  id: z.string(),
  partNumber: z.string().trim().min(1, "Part number is required"),
  partDescription: z.string().trim().min(1, "Description is required"),
  quantity: z.coerce.number({ invalid_type_error: "Quantity must be a number" }).positive("Must be greater than 0"),
  unitPrice: z.coerce.number({ invalid_type_error: "Unit price must be a number" }).nonnegative("Cannot be negative"),
  otherRate: z.coerce.number({ invalid_type_error: "Must be a number" }).nonnegative("Cannot be negative").optional().default(0),
  discount: z.coerce.number({ invalid_type_error: "Must be a number" }).min(0, "Cannot be negative").max(100, "Cannot exceed 100%").optional().default(0),
  availability: z.string().trim().optional().default(""),
  priceWef: z.string().trim().optional().default(""),
  liveStock: z.string().trim().optional().default(""),
  hsnCode: z.string().trim().optional().default(""),
  uom: z.string().trim().optional().default(DEFAULT_UOM),
  gstRate: z.string().trim().optional().default(String(DEFAULT_GST_RATE)),
  group: z.string().trim().optional().default(""),
  subGroup: z.string().trim().optional().default(""),
  lastPurchaseDate: z.string().trim().optional().default(""),
  totalQty: z.string().trim().optional().default(""),
  totalPrice: z.string().trim().optional().default(""),
});

export const quotationSchema = z.object({
  customer: customerInfoSchema,
  quotation: quotationInfoSchema,
  items: z.array(itemRowSchema).min(1, "Add at least one item"),
});

/**
 * Runs the schema and reshapes zod's error tree into a flat map keyed by
 * "section.field" (or "items.<index>.<field>") so form components can look
 * up a single error string per input.
 */
export function validateQuotation(payload) {
  const result = quotationSchema.safeParse(payload);
  if (result.success) {
    return { success: true, data: result.data, errors: {} };
  }

  const errors = {};
  for (const issue of result.error.issues) {
    const path = issue.path.join(".");
    if (!errors[path]) errors[path] = issue.message;
  }
  return { success: false, data: null, errors };
}
