"use client";

import { CardHeader, CardBody } from "@/components/ui/Card";
import Input from "@/components/ui/Input";
import SearchableDropdown from "@/components/ui/SearchableDropdown";
import Select from "@/components/ui/Select";
import { QUOTATION_VALIDITY_OPTIONS } from "@/lib/constants/quotationOptions";
import {
  DIVISIONS,
  ENQUIRY_SOURCES,
  ENQUIRY_GENERATED_BY,
  PAYMENT_TERMS,
  FOLLOWUP_BY,
  REVISE_NUMBERS,
} from "@/constants/masterData";

export default function QuotationInfoSection({
  values,
  errors,
  onChange,
  divisions,
  paymentTerms,
  deliveryTerms,
  enquirySources,
  engineers,
}) {
  return (
    <>
      <CardHeader
        eyebrow="Step 2"
        title="Quotation Information"
        description="Enquiry source, dates, and commercial terms."
      />
      <CardBody className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <SearchableDropdown
          label="Division"
          required
          placeholder="Select division"
          items={DIVISIONS}
          value={values.division}
          error={errors["quotation.division"]}
          onChange={(val) => onChange("division", val)}
        />
        <SearchableDropdown
          label="Source Of Enquiry"
          required
          placeholder="Select source"
          items={ENQUIRY_SOURCES}
          value={values.sourceOfEnquiry}
          error={errors["quotation.sourceOfEnquiry"]}
          onChange={(val) => onChange("sourceOfEnquiry", val)}
        />
        <SearchableDropdown
          label="Enquiry Generated By"
          required
          placeholder="Select engineer"
          items={ENQUIRY_GENERATED_BY}
          value={values.enquiryGeneratedBy}
          error={errors["quotation.enquiryGeneratedBy"]}
          onChange={(val) => onChange("enquiryGeneratedBy", val)}
        />
        <Input
          label="Quotation Date"
          required
          type="date"
          value={values.quotationDate}
          error={errors["quotation.quotationDate"]}
          onChange={(e) => onChange("quotationDate", e.target.value)}
        />
        <Input
          label="Party Reference Number"
          placeholder="PO / Enquiry ref no."
          value={values.partyReferenceNumber}
          error={errors["quotation.partyReferenceNumber"]}
          onChange={(e) => onChange("partyReferenceNumber", e.target.value)}
        />
        <Input
          label="Party Reference Date"
          type="date"
          value={values.partyReferenceDate}
          error={errors["quotation.partyReferenceDate"]}
          onChange={(e) => onChange("partyReferenceDate", e.target.value)}
        />
        <SearchableDropdown
          label="Payment Terms"
          required
          placeholder="Select payment terms"
          items={PAYMENT_TERMS}
          value={values.paymentTerms}
          error={errors["quotation.paymentTerms"]}
          onChange={(val) => onChange("paymentTerms", val)}
        />
        <Select
          label="Quotation Validity"
          required
          placeholder="Select validity"
          options={QUOTATION_VALIDITY_OPTIONS}
          value={values.quotationValidity}
          error={errors["quotation.quotationValidity"]}
          onChange={(e) => onChange("quotationValidity", e.target.value)}
        />
        <Select
          label="Terms Of Delivery"
          required
          placeholder="Select delivery terms"
          options={deliveryTerms}
          value={values.termsOfDelivery}
          error={errors["quotation.termsOfDelivery"]}
          onChange={(e) => onChange("termsOfDelivery", e.target.value)}
        />
        <SearchableDropdown
          label="Quotation Follow-up By"
          placeholder="Select follow-up person"
          items={FOLLOWUP_BY}
          value={values.quotationFollowUpBy}
          error={errors["quotation.quotationFollowUpBy"]}
          onChange={(val) => onChange("quotationFollowUpBy", val)}
        />
        <SearchableDropdown
          label="Revise Number"
          placeholder="Select revision"
          items={REVISE_NUMBERS}
          value={values.reviseNumber}
          error={errors["quotation.reviseNumber"]}
          onChange={(val) => onChange("reviseNumber", val)}
        />
      </CardBody>
    </>
  );
}
