"use client";

import { CardHeader, CardBody } from "@/components/ui/Card";
import Input from "@/components/ui/Input";
import SearchableDropdown from "@/components/ui/SearchableDropdown";
import {
  DIVISIONS,
  ENQUIRY_SOURCES,
  ENQUIRY_GENERATED_BY,
  PAYMENT_TERMS,
  FOLLOWUP_BY,
  REVISE_NUMBERS,
} from "@/constants/masterData";
import { fromCanonicalToDateInput } from "@/lib/utils/dateUtils";

const FOLLOWUP_BY_EXCLUDING_DHEERENDRA_SEN = FOLLOWUP_BY.filter(
  (item) => !/dheerendra\s+sen/i.test(`${item.value} ${item.label}`)
);

export default function QuotationInfoSection({
  values,
  errors,
  onChange,
  divisions,
  paymentTerms,
  enquirySources,
  engineers,
}) {
  return (
    <>
      <CardHeader
        eyebrow="Step 2"
        title="Quotation Information"
        description="Enquiry source, dates, and commercial terms."
      />
      <CardBody className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <SearchableDropdown
          label="Division"
          required
          placeholder="Select division"
          items={DIVISIONS}
          value={values.division}
          error={errors["quotation.division"]}
          onChange={(val) => onChange("division", val)}
        />
        <SearchableDropdown
          label="Source Of Enquiry"
          required
          placeholder="Select source"
          items={ENQUIRY_SOURCES}
          value={values.sourceOfEnquiry}
          error={errors["quotation.sourceOfEnquiry"]}
          onChange={(val) => onChange("sourceOfEnquiry", val)}
        />
        <SearchableDropdown
          label="Enquiry Generated By"
          required
          placeholder="Select engineer"
          items={ENQUIRY_GENERATED_BY}
          value={values.enquiryGeneratedBy}
          error={errors["quotation.enquiryGeneratedBy"]}
          onChange={(val) => onChange("enquiryGeneratedBy", val)}
        />
        <Input
          label="Quotation Date"
          required
          type="date"
          value={fromCanonicalToDateInput(values.quotationDate)}
          error={errors["quotation.quotationDate"]}
          onChange={(e) => onChange("quotationDate", e.target.value)}
        />
        <Input
          label="Party Reference Number"
          placeholder="PO / Enquiry ref no."
          value={values.partyReferenceNumber}
          error={errors["quotation.partyReferenceNumber"]}
          onChange={(e) => onChange("partyReferenceNumber", e.target.value)}
        />
        <Input
          label="Party Reference Date"
          type="date"
          value={fromCanonicalToDateInput(values.partyReferenceDate)}
          error={errors["quotation.partyReferenceDate"]}
          onChange={(e) => onChange("partyReferenceDate", e.target.value)}
        />
        <SearchableDropdown
          label="Payment Terms"
          required
          placeholder="Select payment terms"
          items={PAYMENT_TERMS}
          value={values.paymentTerms}
          error={errors["quotation.paymentTerms"]}
          onChange={(val) => onChange("paymentTerms", val)}
        />
        <Input
          label="Quotation Validity"
          required
          placeholder="e.g. 7 Days, 15 Days, 30 Days, Till Stock Available, Immediate"
          value={values.quotationValidity}
          error={errors["quotation.quotationValidity"]}
          onChange={(e) => onChange("quotationValidity", e.target.value)}
        />
        <Input
          label="Terms Of Delivery"
          required
          placeholder="e.g. Ex-Works, FOB, Door Delivery, CIF"
          value={values.termsOfDelivery}
          error={errors["quotation.termsOfDelivery"]}
          onChange={(e) => onChange("termsOfDelivery", e.target.value)}
        />
        <SearchableDropdown
          label="Quotation Follow-up By"
          placeholder="Select follow-up person"
          items={FOLLOWUP_BY_EXCLUDING_DHEERENDRA_SEN}
          value={values.quotationFollowUpBy}
          error={errors["quotation.quotationFollowUpBy"]}
          onChange={(val) => onChange("quotationFollowUpBy", val)}
        />
      </CardBody>
    </>
  );
}
