"use client";

import { CardHeader, CardBody } from "@/components/ui/Card";
import Input from "@/components/ui/Input";
import Select from "@/components/ui/Select";
import { QUOTATION_VALIDITY_OPTIONS } from "@/lib/constants/quotationOptions";

export default function QuotationInfoSection({
  values,
  errors,
  onChange,
  divisions,
  paymentTerms,
  deliveryTerms,
  enquirySources,
  engineers,
}) {
  return (
    <>
      <CardHeader
        eyebrow="Step 2"
        title="Quotation Information"
        description="Enquiry source, dates, and commercial terms."
      />
      <CardBody className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
        <Select
          label="Division"
          required
          placeholder="Select division"
          options={divisions}
          value={values.division}
          error={errors["quotation.division"]}
          onChange={(e) => onChange("division", e.target.value)}
        />
        <Select
          label="Source Of Enquiry"
          required
          placeholder="Select source"
          options={enquirySources}
          value={values.sourceOfEnquiry}
          error={errors["quotation.sourceOfEnquiry"]}
          onChange={(e) => onChange("sourceOfEnquiry", e.target.value)}
        />
        <Select
          label="Enquiry Generated By"
          required
          placeholder="Select engineer"
          options={engineers.map((e) => ({ value: e.name, label: e.name }))}
          value={values.enquiryGeneratedBy}
          error={errors["quotation.enquiryGeneratedBy"]}
          onChange={(e) => onChange("enquiryGeneratedBy", e.target.value)}
        />
        <Input
          label="Quotation Date"
          required
          type="date"
          value={values.quotationDate}
          error={errors["quotation.quotationDate"]}
          onChange={(e) => onChange("quotationDate", e.target.value)}
        />
        <Input
          label="Party Reference Number"
          placeholder="PO / Enquiry ref no."
          value={values.partyReferenceNumber}
          error={errors["quotation.partyReferenceNumber"]}
          onChange={(e) => onChange("partyReferenceNumber", e.target.value)}
        />
        <Input
          label="Party Reference Date"
          type="date"
          value={values.partyReferenceDate}
          error={errors["quotation.partyReferenceDate"]}
          onChange={(e) => onChange("partyReferenceDate", e.target.value)}
        />
        <Select
          label="Payment Terms"
          required
          placeholder="Select payment terms"
          options={paymentTerms}
          value={values.paymentTerms}
          error={errors["quotation.paymentTerms"]}
          onChange={(e) => onChange("paymentTerms", e.target.value)}
        />
        <Select
          label="Quotation Validity"
          required
          placeholder="Select validity"
          options={QUOTATION_VALIDITY_OPTIONS}
          value={values.quotationValidity}
          error={errors["quotation.quotationValidity"]}
          onChange={(e) => onChange("quotationValidity", e.target.value)}
        />
        <Select
          label="Terms Of Delivery"
          required
          placeholder="Select delivery terms"
          options={deliveryTerms}
          value={values.termsOfDelivery}
          error={errors["quotation.termsOfDelivery"]}
          onChange={(e) => onChange("termsOfDelivery", e.target.value)}
        />
        <Input
          label="Quotation Follow-up By"
          type="date"
          value={values.quotationFollowUpBy}
          error={errors["quotation.quotationFollowUpBy"]}
          onChange={(e) => onChange("quotationFollowUpBy", e.target.value)}
        />
        <Input
          label="Revise Number"
          placeholder="R0"
          value={values.reviseNumber}
          error={errors["quotation.reviseNumber"]}
          onChange={(e) => onChange("reviseNumber", e.target.value)}
        />
      </CardBody>
    </>
  );
}
